//Get Current User
export const CURRENT_USER_REQUEST = "CURRENT_USER_REQUEST";
export const CURRENT_USER_SUCCESS = "CURRENT_USER_SUCCESS";
export const CURRENT_USER_FAIL = "CURRENT_USER_FAIL";
export const CURRENT_USER_RESET = "CURRENT_USER_RESET";

//========> Craete profile<=============
export const PROFILE_CREATE_REQUEST = "PROFILE_CREATE_REQUEST";
export const PROFILE_CREATE_SUCCESS = "PROFILE_CREATE_SUCCESS";
export const PROFILE_CREATE_FAIL = "PROFILE_CREATE_FAIL";
export const PROFILE_CREATE_RESET = "PROFILE_CREATE_RESET";

//==============> Delete Profile<================
export const DELETE_PROFILE_REQUEST = "DELETE_PROFILE_REQUEST";
export const DELETE_PROFILE_SUCCESS = "DELETE_PROFILE_SUCCESS";
export const DELETE_PROFILE_FAIL = "DELETE_PROFILE_FAIL";

//==============> Add Experience <================
export const ADD_EXPERIENCE_REQUEST = "ADD_EXPERIENCE_REQUEST";
export const ADD_EXPERIENCE_SUCCESS = "ADD_EXPERIENCE_SUCCESS";
export const ADD_EXPERIENCE_FAIL = "ADD_EXPERIENCE_FAIL";
export const ADD_EXPERIENCE_RESET = "ADD_EXPERIENCE_RESET";

//==============> Add Education <================
export const ADD_EDUCATION_REQUEST = "ADD_EDUCATION_REQUEST";
export const ADD_EDUCATION_SUCCESS = "ADD_EDUCATION_SUCCESS";
export const ADD_EDUCATION_FAIL = "ADD_EDUCATION_FAIL";
export const ADD_EDUCATION_RESET = "ADD_EDUCATION_RESET";

//==============> Delete Experience <==============
export const DELETE_EXPERIENCE_REQUEST = "DELETE_EXPERIENCE_REQUEST";
export const DELETE_EXPERIENCE_SUCCESS = "DELETE_EXPERIENCE_SUCCESS";
export const DELETE_EXPERIENCE_FAIL = "DELETE_EXPERIENCE_REQUEST";

//=============> Delete Education <===========
export const DELETE_EDUCATION_REQUEST = "DELETE_EDUCATION_REQUEST";
export const DELETE_EDUCATION_SUCCESS = "DELETE_EDUCATION_SUCCESS";
export const DELETE_EDUCATION_FAIL = "DELETE_EDUCATION_REQUEST";

//==============> Get all Profiles Users <==============
export const GET_ALL_PROFILE_USERS_REQUEST = "GET_ALL_PROFILE_USERS_REQUEST";
export const GET_ALL_PROFILE_USERS_SUCCESS = "GET_ALL_PROFILE_USERS_SUCCESS";
export const GET_ALL_PROFILE_USERS_FAIL = "GET_ALL_PROFILE_USERS_REQUEST";

//============== Get profile user by id<==============
export const GET_PROFILE_USER_REQUEST = "GET_PROFILE_USER_REQUEST";
export const GET_PROFILE_USER_SUCCESS = "GET_PROFILE_USER_SUCCESS";
export const GET_PROFILE_USER_FAIL = "GET_PROFILE_USER_REQUEST";
